#!/bin/csh -v

######################### USER INPUT #######################################################
#setenv  EXPID   GiOCEAN_e1
#setenv  EXPDIR  /discover/nobackup/projects/gmao/merra2-ocean/GiOCEAN_e1
#setenv  GEOSDIR /discover/nobackup/projects/gmao/merra2-ocean/yuri-s2s3-unstable-SLES12/GEOSodas

setenv ODAS_group           g0609
setenv ODAS_qos             gmaofcst
setenv ODAS_Ne              20                # Ensemble size (Hard coded in params_letkf.f90)
setenv ODAS_Nx              1440              # 
setenv ODAS_Ny              721               # Grid size hard coded in params_model.f90
setenv ODAS_Nz              50                #
setenv ODAS_NPE_ocean       256               # Number of core used for oceanda.x
setenv ODAS_NPE_cice        256               # Number of core used for oceanda.x when assimilating sea-ice
#setenv ODAS_RC              /gpfsm/dnb78s2/projects/p26/ehackert/GEOSodas-V3/RC/OCEAN_DAS_RC_V2_INTERP_TO_V3/  # Location of static members, mappings, grids, FOR THE V2 INTERPED TO V3
setenv ODAS_RC              /gpfsm/dnb78s2/projects/p26/ehackert/GEOSodas-V3/RC/OCEAN_DAS_RC_BASE_3_ALL_MONTHS/  # Location of static members, mappings, grids, FOR KAZUMI's BASE_3 FORECASTS
setenv ODAS_GRID_TYPE       reg               # type of grid, tri (tripolar) or reg (regular lat-lon) !!!!! OBSOLETE, not supporting tripolar !!!!!
setenv ODAS_logit_transform False             # logit transform for ice fraction                      !!!!! OBSOLETE, not supporting logit transform !!!!!
setenv ODAS_regrid          True              # regrid from analysis grid to model grid               !!!!! OBSOLETE, always assumes the need to regrid !!!!!
setenv ODAS_NDAYS	    0.125             # 1/2 the frequency of the launch of the observers.  
setenv ODAS_T_prof_sigo     10.0 #0.25        # Basic obs error for temperature profiles [deg C]
setenv ODAS_S_prof_sigo     10.0 #0.025       #        "              salinity       "    [psu]
setenv ODAS_ADT_sigo        0.2
setenv ODAS_SSS_sigo        1.0               # obs error scaling factor for L3 Aq. data
setenv ODAS_rewind          True              # True: Rewinds to the start of the window              !!!!! OBSOLETE !!!!!
setenv ODAS_IAU             True              # True: Use iau, restoring period set to 18 hours   !!!!! No IAU NOT SUPPOETED !!!!
setenv ODAS_IAU_TIME        18                # IAU restors increment up to ODAS_IAU_TIME in UTC hours
setenv ODAS_do_aice         True              # True: 
setenv ODAS_do_aice_nudging False             # True:  USE FALSE WHEN DUAL OCEAN IS RUNNING
setenv ODAS_do_hice         False             # True: 
setenv ODAS_dt_restore_sst  24                # Restoring time scale for the sst nudging
setenv ODAS_dt_restore_sss 1440               # 60day*24hr/day=1440 Restoring time scale for the sss nudging
setenv ODAS_loc_max         400.0             # Max horizontal localizationlength scale [km]
setenv ODAS_loc_min         200.0             # Min horizontal localizationlength scale [km]
setenv ODAS_loc_max_cice    200.0             # Max horizontal localizationlength scale [km]
setenv ODAS_loc_min_cice    200.0             # Min horizontal localizationlength scale [km]

setenv ODAS_do_reinit       False             # True: input to anaice2rst.x is from ice analysis
                                              #       supposed to be the case for 5-day reinit    
                                              # False: input to anaice2rst.x is from M2 ice frac
                                              #       for continuous analysis to be north pole
                                              #       hole free 
setenv IN_LINE              True              # False: runs multiple observer jobs. NOT recomended for MILAN nodes
                                              # True: runs observers in line (within model job, model pauses to wait until complete). Recomended for MILAN nodes
setenv ODAS_CONSTR          "[cas]"       # Only used when IN_LINE is False. Must be same node constraint as in gcm_run.j
                                              # Not recomended for use in Milan.
setenv BOMB_ON_SIGO         True              # True: BOMBS the model due to not meeting sigo ADT requirements (as before)
                                              # False: Skips ADT observations that fail sigo requirements. Does not bomb.
# Varibles used for salinity relaxation
setenv SSSVAR                LEVITUSSC        # use SMAP seasonal cycle for SSS relaxation
                                              #   other options 
                                              # AQAURIUSSC - for SSS relax to AQUARIUS Seasonal cycle
                                              # SMAPSC     - for SSS relax to SMAP seasonal cycle
                                              # LEVITUSSC  - for SSS relax to LEVITUS WOA13 seasonal cycle
                                              # AQAURIUS   - for SSS relax to AQUARIUS interannual data
                                              # SMAP       - for SSS relax to SMAP interannual data

#Switch for assimilation of obs. Boolean, T or F
setenv ODAS_ACTIVE_Tprof    True                 # Temperature profile
setenv ODAS_ACTIVE_Sprof    True                 # Salinity profile
setenv ODAS_ACTIVE_ADT      True                 # Absolute Dynamic Topography
setenv ODAS_ACTIVE_SST      True                 # 
setenv ODAS_ACTIVE_SSS      True                 #
setenv ODAS_ACTIVE_AICE     True                 # Sea-ice concentration
setenv ODAS_ACTIVE_HICE     False                # Sea-ice thickness 

#  USE SOME OLD OBSERVERS FOR OSE EXPERIMENTS
setenv ODAS_USE_OLD_OBS     False                # Replace obs with old value
setenv ODAS_DIR_OLD_OBS     "/gpfsm/dnb42/projects/p17/ehackert/geos5/exp/eh020/ocean_das/"     # if ODAS_USE_OLD_OBS is true look here to replace the obs files
#setenv ODAS_DIR_OLD_OBS     "/gpfsm/dnb42/projects/p17/ehackert/geos5/exp/eh025/ocean_das/"

#  test to see if you want to output the OMA observers
setenv ODAS_OUTPUT_OMA      True                # output OMA observers in oda_run.j

#List of observation platforms
setenv ODAS_OBS_TYPE_1 "Argo M2-SST XBT-SYN-S CTD XBT TAO PIRATA RAMA Jason-1 Jason-2 Jason-3 Saral Sentinel-3a ERS-1 ERS-2 TOPEX GEOSAT-2 Envisat HY-2A CryoSat-2 TOPEX-N Envisat-N Jason-1-N Jason-1G Jason-2-N CryoSat-2-N NASA-TEAM-2 SMOS AQUARIUS SMAPV5.0"
setenv HICE_DATADIR      /discover/nobackup/bzhao/ObservationData/CRYOSAT2/o1440x1080
setenv HICE_HASMASK      True
######################### END USER INPUT ####################################################

#######################################################################
#              Environment Variables
#######################################################################

#setenv    ODAS_GRID        $ODAS_RC/BKGERR/anom-
setenv    SCRDIR           $EXPDIR/scratch
setenv    ODAS_BIN         $GEOSDIR/Linux/bin
setenv    UMD_LETKFRC      $EXPDIR/ocean_das/UMD_Etc/UMD_rc/
setenv    UMD_LETKFUTILS   $EXPDIR/ocean_das/UMD_Etc/UMD_utils/
setenv    UMD_LETKFSCRIPTS $EXPDIR/ocean_das/UMD_Etc/scripts/
setenv    UMD_LETKFSRC     $EXPDIR/ocean_das/UMD_Etc/UMD_oletkf/
setenv    UMD_LETKFPLOT    $UMD_LETKFUTILS/plot/
setenv    UMD_LETKFSCRDIR  $EXPDIR/ocean_das    # work dir for the ocean das

#setenv    JOB_NDAYS        `cat CAP.rc | grep JOB_SGMT: | cut -d: -f2 | cut -c12-13`                       #Assumes job segments is in days
setenv    JOB_NDAYS        `grep JOB_SGMT CAP.rc | sed 's/.*://' | sed 's/000000//' | sed 's/000000//'`   #`cat CAP.rc | grep JOB_SGMT: | cut -d: -f2 | cut -c2-9`                          #Assumes job segments is in days
#setenv    OBSERVER_FREQ    `cat HISTORY.rc | grep oletkf_ocn2d.frequency: | cut -d: -f2 | cut -c3-4`      #Assumes observer frequency is in hours
setenv    OBSERVER_FREQ    `cat HISTORY.rc | grep ocn_inst_6hr_glo_L1440x721_slv.frequency: | cut -d: -f2 | cut -c3-4`      #Assumes observer frequency is in hours
setenv    OCEAN_Nx         `grep  OGCM_IM: $SCRDIR/AGCM.rc | cut -d':' -f2`
setenv    OCEAN_Ny         `grep  OGCM_JM: $SCRDIR/AGCM.rc | cut -d':' -f2`
setenv    OCEAN_Nz         `grep  OGCM_LM: $SCRDIR/AGCM.rc | cut -d':' -f2`

#Set basename for the history collections used by the ocean das  

setenv OCNCTRL  ocn_inst_6hr_glo_T1440x1080_z50
setenv OCN3D    ocn_inst_6hr_glo_L1440x721_z50
setenv OCN2D    ocn_inst_6hr_glo_L1440x721_slv
setenv SEAICE   ice_inst_6hr_glo_L1440x721_slv

chmod +x ${UMD_LETKFUTILS}/mean_ods.py
chmod +x ${UMD_LETKFUTILS}/dynamic_height.py
chmod +x ${UMD_LETKFUTILS}/rst2hist.py

setenv RUN_CMD         "mpirun -np "

setenv DO_BIAS_CORR False
setenv DO_INCR_BOX  False
setenv WESTLON -70
setenv EASTLON -20
setenv SOUTHLAT 45
setenv NORTHLAT 65
setenv BOXSCALE  0

