#!/bin/csh -f

set statsrc = $1

# Get Experiments to plot
# -----------------------
set allexps = `cat $statsrc | grep DSC | grep -v \# | grep -v \*`
@   numexps = $#allexps / 2

   set DSC0 = `cat $statsrc | grep DSC0 | grep -v \#  | grep -v \* | cut -d: -f2`
   set EXPS = ''
   @   n = 2
while ($n <= $numexps )
   @   m = $n - 1
   set EXPS = "$EXPS `cat $statsrc | grep DSC$m | grep -v \#  | grep -v \* | cut -d: -f2`"
   @   n = $n + 1
end
set EXPS = `echo $EXPS`

echo DSC0: $DSC0
echo EXPS: $EXPS

set STATSDIR = corcmp
cd $STATSDIR

set files  = `/bin/ls -1 stats_*_*_*_*_*.gif`

if( $#files >= 1 ) then
set SEASON = `echo $files[1] | cut -d_ -f6 | cut -d. -f1`

foreach VAR ('corcmp' 'rmscmp')
foreach EXP ($EXPS)

#montage stats_hght_${VAR}_GLO_500_${SEASON}.gif ${DSC0}_${EXP}_stats_hght_${VAR}*GLO* ${DSC0}_${EXP}_stats_uwnd_${VAR}*GLO* ${DSC0}_${EXP}_stats_vwnd_${VAR}*GLO* ${DSC0}_${EXP}_stats_tmpu_${VAR}*GLO* ${DSC0}_${EXP}_stats_sphu_${VAR}*GLO* \
#        stats_hght_${VAR}_NHE_500_${SEASON}.gif ${DSC0}_${EXP}_stats_hght_${VAR}*NHE* ${DSC0}_${EXP}_stats_uwnd_${VAR}*NHE* ${DSC0}_${EXP}_stats_vwnd_${VAR}*NHE* ${DSC0}_${EXP}_stats_tmpu_${VAR}*NHE* ${DSC0}_${EXP}_stats_sphu_${VAR}*NHE* \
#        stats_hght_${VAR}_SHE_500_${SEASON}.gif ${DSC0}_${EXP}_stats_hght_${VAR}*SHE* ${DSC0}_${EXP}_stats_uwnd_${VAR}*SHE* ${DSC0}_${EXP}_stats_vwnd_${VAR}*SHE* ${DSC0}_${EXP}_stats_tmpu_${VAR}*SHE* ${DSC0}_${EXP}_stats_sphu_${VAR}*SHE* \
#        stats_tmpu_${VAR}_TRO_300_${SEASON}.gif ${DSC0}_${EXP}_stats_hght_${VAR}*TRO* ${DSC0}_${EXP}_stats_uwnd_${VAR}*TRO* ${DSC0}_${EXP}_stats_vwnd_${VAR}*TRO* ${DSC0}_${EXP}_stats_tmpu_${VAR}*TRO* ${DSC0}_${EXP}_stats_sphu_${VAR}*TRO* \
#        -tile 6x4 -geometry +0+0 ${DSC0}_${EXP}_${VAR}_${SEASON}_montage.gif  &

montage ${DSC0}_${EXP}_stats_hght_${VAR}*GLO* ${DSC0}_${EXP}_stats_uwnd_${VAR}*GLO* ${DSC0}_${EXP}_stats_vwnd_${VAR}*GLO* ${DSC0}_${EXP}_stats_tmpu_${VAR}*GLO* ${DSC0}_${EXP}_stats_sphu_${VAR}*GLO* \
        ${DSC0}_${EXP}_stats_hght_${VAR}*NHE* ${DSC0}_${EXP}_stats_uwnd_${VAR}*NHE* ${DSC0}_${EXP}_stats_vwnd_${VAR}*NHE* ${DSC0}_${EXP}_stats_tmpu_${VAR}*NHE* ${DSC0}_${EXP}_stats_sphu_${VAR}*NHE* \
        ${DSC0}_${EXP}_stats_hght_${VAR}*SHE* ${DSC0}_${EXP}_stats_uwnd_${VAR}*SHE* ${DSC0}_${EXP}_stats_vwnd_${VAR}*SHE* ${DSC0}_${EXP}_stats_tmpu_${VAR}*SHE* ${DSC0}_${EXP}_stats_sphu_${VAR}*SHE* \
        ${DSC0}_${EXP}_stats_hght_${VAR}*TRO* ${DSC0}_${EXP}_stats_uwnd_${VAR}*TRO* ${DSC0}_${EXP}_stats_vwnd_${VAR}*TRO* ${DSC0}_${EXP}_stats_tmpu_${VAR}*TRO* ${DSC0}_${EXP}_stats_sphu_${VAR}*TRO* \
        -tile 5x4 -geometry +0+0 ${DSC0}_${EXP}_${VAR}_${SEASON}_montage.gif  &
end
end
wait
endif

